# Default values for etcd-carry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: xakdwch5/etcd-carry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Etcd PKI configmap should be created in advance
existingPkiConfigmap: ~

# mirror rules and encryptionProviderConfig should be created in advance
existingConfigmap: ~

endpoints:
  source: ~
  dest: ~

env:
  ETCDCTL_API: "3"

resources: {}
  #limits:
  #  cpu: 1000m
  #  memory: 1000Mi
  #requests:
  #  cpu: 200m
  #  memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
