apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-carry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd-carry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd-carry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "etcd-carry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /etcd-carry
          args:
            - --source-cacert=/etc/etcd-carry/etcd/source/ca.crt
            - --source-cert=/etc/etcd-carry/etcd/source/server.crt
            - --source-key=/etc/etcd-carry/etcd/source/server.key
            - --source-endpoints={{ .Values.endpoints.source }}
            - --dest-cacert=/etc/etcd-carry/etcd/dest/ca.crt
            - --dest-cert=/etc/etcd-carry/etcd/dest/server.crt
            - --dest-key=/etc/etcd-carry/etcd/dest/server.key
            - --dest-endpoints={{ .Values.endpoints.dest }}
            - --encryption-provider-config=/etc/etcd-carry/kube/secrets-encryption.yaml
            - --mirror-rule=/etc/etcd-carry/rules.yaml
          env:
            - name: ETCDCTL_API
              value: {{ .Values.env.ETCDCTL_API | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pki
              mountPath: /etc/etcd-carry/etcd/source/ca.crt
              subPath: source-ca.crt
            - name: pki
              mountPath: /etc/etcd-carry/etcd/source/server.crt
              subPath: source-server.crt
            - name: pki
              mountPath: /etc/etcd-carry/etcd/source/server.key
              subPath: source-server.key
            - name: pki
              mountPath: /etc/etcd-carry/etcd/dest/ca.crt
              subPath: dest-ca.crt
            - name: pki
              mountPath: /etc/etcd-carry/etcd/dest/server.crt
              subPath: dest-server.crt
            - name: pki
              mountPath: /etc/etcd-carry/etcd/dest/server.key
              subPath: dest-server.key
            - name: config
              mountPath: /etc/etcd-carry/kube/secrets-encryption.yaml
              subPath: secrets-encryption.yaml
            - name: config
              mountPath: /etc/etcd-carry/rules.yaml
              subPath: rules.yaml
            - mountPath: /etc/localtime
              name: lt-config
            - mountPath: /etc/timezone
              name: tz-config
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: pki
          configMap:
            name: {{ include "etcd-carry.pki" . }}
        - name: config
          configMap:
            name: {{ include "etcd-carry.config" . }}
        - name: lt-config
          hostPath:
            path: /etc/localtime
        - name: tz-config
          hostPath:
            path: /etc/timezone
